services:
  mail:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aerolinea-mail
    hostname: mail
    domainname: ${DOMAIN:-aerolinea.redes.test}
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:-aerolinea.redes.test}
      BASE_DN: ${BASE_DN:-dc=aerolinea,dc=redes,dc=test}
      LDAP_HOST: ${LDAP_HOST:-ldap.aerolinea.redes.test}
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${IMAP_PORT:-143}:143"
      - "${SUBMISSION_PORT:-587}:587"
    dns:
      - ${DNS_IP:-192.168.50.10}
    volumes:
      - mail_data:/var/mail/vhosts

volumes:
  mail_data:
