LDAPCacheEntries -1
LDAPOpCacheEntries -1

<VirtualHost *:80>
    ServerName www.aerolinea.redes.test
    DocumentRoot /var/www/aerolinea

    ErrorLog ${APACHE_LOG_DIR}/aerolinea-error.log
    CustomLog ${APACHE_LOG_DIR}/aerolinea-access.log combined
    LogLevel warn auth_form:info authnz_ldap:info ldap:info

    <Directory /var/www/aerolinea>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>

    <Directory /var/www/aerolinea/privado>
        <Files "usuario.json">
            Options +Includes
            SetOutputFilter INCLUDES
        </Files>
    </Directory>

    Session On
    SessionCookieName aerolinea_sesion path=/;HttpOnly;SameSite=Strict
    SessionCryptoPassphraseFile /etc/apache2/aerolinea-session.key
    SessionMaxAge 1800

    <LocationMatch "^/(privado|dologin|logout)">
        AuthType form
        AuthName aerolinea
        AuthFormProvider ldap
        AuthLDAPURL "ldap://ldap.aerolinea.redes.test/ou=People,dc=aerolinea,dc=redes,dc=test?uid,cn,mail?one"
    </LocationMatch>

    <Location /privado>
        AuthFormLoginRequiredLocation /login/
        Require valid-user
    </Location>

    <Location /dologin>
        SetHandler form-login-handler
        AuthFormLocation httpd_location_deshabilitado
        AuthFormLoginRequiredLocation /login/?error=1
        AuthFormLoginSuccessLocation /privado/
    </Location>

    <Location /logout>
        SetHandler form-logout-handler
        AuthFormLogoutLocation /
        SessionMaxAge 1
    </Location>
</VirtualHost>
